import type { PlayerPopularity } from '../types/player';

/**
 * 현역 선수 444명 인기도 시드값
 * - 상위 ~80명: 실제 인지도 기반 수동 조정
 * - 나머지: OVR·팀 마켓·팀 내 순위·나이 기반 자동 계산
 * - 키: meta_players.name (한국어 표기)
 *
 * local   : 연고지 인기 (관중·MD 직결)
 * national: 전국/글로벌 인지도 (스폰서십·MD)
 */
export const PLAYER_POPULARITY_SEEDS: ReadonlyMap<string, PlayerPopularity> = new Map([

    // ─── Tier S — 글로벌 슈퍼스타 ───
    ['르브론 제임스', { local:  88, national:  97 }],
    ['스테판 커리', { local:  95, national:  95 }],
    ['야니스 안테토쿤보', { local:  92, national:  91 }],
    ['케빈 듀란트', { local:  68, national:  90 }],
    ['루카 돈치치', { local:  90, national:  89 }],

    // ─── Tier A — 리그 최정상급 스타 ───
    ['니콜라 요키치', { local:  80, national:  83 }],
    ['제임스 하든', { local:  64, national:  82 }],
    ['빅터 웸반야마', { local:  80, national:  81 }],
    ['카이리 어빙', { local:  70, national:  81 }],
    ['셰이 길저스-알렉산더', { local:  82, national:  80 }],
    ['앤서니 에드워즈', { local:  85, national:  79 }],
    ['제이슨 테이텀', { local:  88, national:  78 }],
    ['조엘 엠비드', { local:  84, national:  78 }],
    ['카와이 레너드', { local:  72, national:  78 }],
    ['앤서니 데이비스', { local:  74, national:  76 }],
    ['자 모란트', { local:  82, national:  76 }],
    ['데미안 릴라드', { local:  68, national:  76 }],
    ['도노반 미첼', { local:  78, national:  72 }],
    ['지미 버틀러 3세', { local:  70, national:  72 }],
    ['데빈 부커', { local:  82, national:  72 }],
    ['제일런 브런슨', { local:  85, national:  72 }],

    // ─── Tier B — 올스타급 ───
    ['라멜로 볼', { local:  78, national:  70 }],
    ['자이언 윌리엄슨', { local:  80, national:  70 }],
    ['클레이 탐슨', { local:  64, national:  70 }],
    ['제일런 브라운', { local:  82, national:  70 }],
    ['타이리스 할리버튼', { local:  80, national:  70 }],
    ['트레이 영', { local:  82, national:  68 }],
    ['폴 조지', { local:  65, national:  68 }],
    ['자말 머레이', { local:  78, national:  68 }],
    ['러셀 웨스트브룩', { local:  52, national:  68 }],
    ['타이리스 맥시', { local:  78, national:  66 }],
    ['드레이먼드 그린', { local:  65, national:  66 }],
    ['뱀 아데바요', { local:  78, national:  65 }],
    ['자렌 잭슨 주니어', { local:  75, national:  65 }],
    ['더마 드로잔', { local:  68, national:  65 }],
    ['파스칼 시아캄', { local:  70, national:  65 }],
    ['칼-앤서니 타운스', { local:  70, national:  65 }],
    ['파올로 반케로', { local:  78, national:  65 }],
    ['디애런 팍스', { local:  73, national:  64 }],
    ['알페렌 센군', { local:  75, national:  63 }],
    ['케이드 커닝햄', { local:  75, national:  63 }],
    ['타일러 히로', { local:  72, national:  62 }],
    ['브래들리 빌', { local:  58, national:  62 }],
    ['쳇 홈그렌', { local:  72, national:  62 }],
    ['오스틴 리브스', { local:  72, national:  62 }],
    ['잭 라빈', { local:  68, national:  60 }],
    ['제일런 윌리엄스', { local:  72, national:  60 }],
    ['다리우스 갈란드', { local:  72, national:  59 }],
    ['줄리어스 랜들', { local:  63, national:  58 }],
    ['루디 고베어', { local:  62, national:  58 }],
    ['스카티 반스', { local:  72, national:  58 }],
    ['프란츠 바그너', { local:  72, national:  58 }],
    ['도만타스 사보니스', { local:  68, national:  58 }],
    ['즈루 홀리데이', { local:  62, national:  58 }],

    // ─── Tier C — 주전급 ───
    ['브랜던 잉그램', { local:  62, national:  56 }],
    ['앤드류 위긴스', { local:  65, national:  56 }],
    ['미칼 브리지스', { local:  65, national:  56 }],
    ['OG 아누노비', { local:  65, national:  56 }],
    ['크리스탑스 포르징기스', { local:  60, national:  56 }],
    ['애런 고든', { local:  68, national:  55 }],
    ['크리스 미들턴', { local:  65, national:  55 }],
    ['쿠퍼 플래그', { local:  65, national:  55 }],
    ['데릭 화이트', { local:  68, national:  55 }],
    ['코비 화이트', { local:  68, national:  54 }],
    ['라우리 마카넨', { local:  65, national:  53 }],
    ['아멘 탐슨', { local:  65, national:  52 }],
    ['데스몬드 베인', { local:  65, national:  52 }],
    ['브랜던 밀러', { local:  68, national:  52 }],
    ['RJ 배럿', { local:  65, national:  52 }],
    ['마이클 포터 주니어', { local:  62, national:  52 }],
    ['마일스 터너', { local:  65, national:  52 }],
    ['디존테 머레이', { local:  65, national:  52 }],
    ['조던 풀', { local:  58, national:  52 }],
    ['마일스 브리지스', { local:  65, national:  52 }],
    ['조쉬 기디', { local:  65, national:  52 }],
    ['에반 모블리', { local:  65, national:  52 }],
    ['니콜라 부셰비치', { local:  65, national:  52 }],
    ['재럿 앨런', { local:  65, national:  50 }],
    ['임마누엘 퀵클리', { local:  62, national:  48 }],
    ['브로니 제임스', { local:  52, national:  42 }],

    // ─── Tier D — 로테이션 ───
    ['제일런 듀렌', { local:  59, national:  34 }],
    ['데니 아브디야', { local:  67, national:  33 }],
    ['제일런 존슨', { local:  60, national:  30 }],
    ['타나시스 아테토쿤보', { local:  38, national:  28 }],
    ['딜런 브룩스', { local:  57, national:  25 }],

    // ─── Tier E — 엔드오브벤치 ───
    ['노먼 파웰', { local:  55, national:  24 }],
    ['이비차 주바치', { local:  56, national:  24 }],
    ['그레이슨 알렌', { local:  52, national:  23 }],
    ['토바이어스 해리스', { local:  53, national:  23 }],
    ['앤드류 넴하드', { local:  52, national:  23 }],
    ['닉 클랙스턴', { local:  56, national:  22 }],
    ['요나스 발렌슈나스', { local:  50, national:  22 }],
    ['니켈 알렉산더-워커', { local:  50, national:  22 }],
    ['온예카 오콩우', { local:  48, national:  21 }],
    ['애런 니스미스', { local:  48, national:  21 }],
    ['조쉬 하트', { local:  52, national:  21 }],
    ['디안드레 에이튼', { local:  52, national:  21 }],
    ['트레이 머피 III', { local:  48, national:  21 }],
    ['잭 이디', { local:  50, national:  21 }],
    ['콜린 섹스턴', { local:  49, national:  20 }],
    ['데니스 슈뢰더', { local:  49, national:  20 }],
    ['키욘테 조지', { local:  53, national:  20 }],
    ['나즈 리드', { local:  46, national:  20 }],
    ['제이든 맥다니엘스', { local:  46, national:  20 }],
    ['어사르 톰슨', { local:  47, national:  20 }],
    ['유서프 너키치', { local:  49, national:  20 }],
    ['디안드레 헌터', { local:  46, national:  20 }],
    ['셰이던 샤프', { local:  53, national:  20 }],
    ['아이재아 하텐슈타인', { local:  47, national:  19 }],
    ['페이튼 프리차드', { local:  48, national:  19 }],
    ['스티븐 아담스', { local:  48, national:  19 }],
    ['조너선 쿠밍가', { local:  49, national:  19 }],
    ['앤퍼니 사이몬스', { local:  47, national:  19 }],
    ['제레미 그랜트', { local:  46, national:  18 }],
    ['야콥 퍼들', { local:  45, national:  18 }],
    ['디안젤로 러셀', { local:  45, national:  18 }],
    ['알렉스 카루소', { local:  44, national:  18 }],
    ['케빈 포터 주니어', { local:  44, national:  18 }],
    ['T.J. 맥코넬', { local:  45, national:  18 }],
    ['P.J. 워싱턴', { local:  45, national:  18 }],
    ['미첼 로빈슨', { local:  44, national:  17 }],
    ['돈테 디빈첸조', { local:  43, national:  17 }],
    ['디앤서니 멜튼', { local:  44, national:  17 }],
    ['마크 윌리엄스', { local:  46, national:  17 }],
    ['캠 토마스', { local:  48, national:  17 }],
    ['타이 제롬', { local:  41, national:  17 }],
    ['게르숑 야부셀레', { local:  44, national:  17 }],
    ['세드릭 카워드', { local:  45, national:  17 }],
    ['에이제이 미첼', { local:  45, national:  17 }],
    ['팻 스펜서', { local:  44, national:  17 }],
    ['다이슨 다니엘스', { local:  45, national:  17 }],
    ['루이 하치무라', { local:  46, national:  17 }],
    ['카일 쿠즈마', { local:  41, national:  17 }],
    ['퀸텐 포스트', { local:  46, national:  17 }],
    ['키건 머레이', { local:  43, national:  17 }],
    ['아이재아 조', { local:  42, national:  17 }],
    ['루크 코넷', { local:  41, national:  17 }],
    ['트레 존스', { local:  41, national:  16 }],
    ['쿠엔틴 그라임스', { local:  42, national:  16 }],
    ['케빈 허더', { local:  41, national:  16 }],
    ['조던 클락슨', { local:  41, national:  16 }],
    ['제일런 석스', { local:  43, national:  16 }],
    ['게이브 빈센트', { local:  41, national:  16 }],
    ['마일스 맥브라이드', { local:  41, national:  16 }],
    ['맥스 크리스티', { local:  42, national:  16 }],
    ['콜린 길레스피', { local:  41, national:  16 }],
    ['존 콜린스', { local:  42, national:  16 }],
    ['자레드 밴더빌트', { local:  41, national:  16 }],
    ['크리스찬 브라운', { local:  41, national:  16 }],
    ['잭슨 헤이즈', { local:  42, national:  16 }],
    ['마커스 스마트', { local:  42, national:  16 }],
    ['샘 하우저', { local:  42, national:  16 }],
    ['아요 도순무', { local:  43, national:  16 }],
    ['개리 페이튼 2세', { local:  42, national:  16 }],
    ['아이재아 잭슨', { local:  42, national:  16 }],
    ['버디 힐드', { local:  41, national:  16 }],
    ['브랜던 윌리엄스', { local:  42, national:  16 }],
    ['던컨 로빈슨', { local:  40, national:  16 }],
    ['코리 키스퍼트', { local:  42, national:  16 }],
    ['데이비온 미첼', { local:  41, national:  16 }],
    ['브루스 브라운', { local:  41, national:  16 }],
    ['아이재아 스튜어트', { local:  43, national:  16 }],
    ['E.J.리델', { local:  45, national:  16 }],
    ['다니엘 개포드', { local:  42, national:  16 }],
    ['애런 위긴스', { local:  41, national:  16 }],
    ['제이든 아이비', { local:  43, national:  16 }],
    ['웬델 카터 주니어', { local:  40, national:  15 }],
    ['알렉스 사르', { local:  49, national:  15 }],
    ['로이스 오닐', { local:  39, national:  15 }],
    ['팀 하더웨이 주니어', { local:  39, national:  15 }],
    ['데빈 바셀', { local:  40, national:  15 }],
    ['브랜딘 포지엠스키', { local:  43, national:  15 }],
    ['루겐츠 도트', { local:  39, national:  15 }],
    ['니미아스 퀘타', { local:  39, national:  15 }],
    ['모세스 무디', { local:  43, national:  15 }],
    ['키온 엘리스', { local:  40, national:  15 }],
    ['호세 알바라도', { local:  39, national:  15 }],
    ['딘 웨이드', { local:  40, national:  15 }],
    ['타이어스 존스', { local:  40, national:  15 }],
    ['해리슨 반즈', { local:  40, national:  15 }],
    ['나지 마샬', { local:  40, national:  15 }],
    ['바비 포르티스', { local:  40, national:  15 }],
    ['마타스 부젤리스', { local:  44, national:  15 }],
    ['샘 메릴', { local:  40, national:  15 }],
    ['안드레 드러먼드', { local:  40, national:  15 }],
    ['케일럽 마틴', { local:  40, national:  15 }],
    ['테렌스 맨', { local:  40, national:  15 }],
    ['데이런 샤프', { local:  42, national:  15 }],
    ['켈렐 웨어', { local:  45, national:  15 }],
    ['크리스 던', { local:  40, national:  15 }],
    ['켈리 우브레 주니어', { local:  40, national:  15 }],
    ['그랜트 윌리엄스', { local:  40, national:  15 }],
    ['로버트 윌리엄스 III', { local:  40, national:  15 }],
    ['제이크 라라비아', { local:  43, national:  15 }],
    ['CJ 맥컬럼', { local:  45, national:  15 }],
    ['스테폰 캐슬', { local:  44, national:  15 }],
    ['자이어 윌리엄스', { local:  40, national:  14 }],
    ['말릭 몽크', { local:  38, national:  14 }],
    ['트레이시 잭슨-데이비스', { local:  37, national:  14 }],
    ['조크 렌데일', { local:  36, national:  14 }],
    ['모리츠 와그너', { local:  38, national:  14 }],
    ['마빈 베글리 III', { local:  37, national:  14 }],
    ['비트 크레이치', { local:  36, national:  14 }],
    ['닉 리차즈', { local:  37, national:  14 }],
    ['트레이 제이미슨 III', { local:  37, national:  14 }],
    ['트리스탄 다 실바', { local:  39, national:  14 }],
    ['타이리스 마틴', { local:  36, national:  14 }],
    ['켄타비우스 칼드웰-포프', { local:  38, national:  14 }],
    ['페이튼 왓슨', { local:  40, national:  14 }],
    ['트렌던 왓포드', { local:  37, national:  14 }],
    ['루크 케너드', { local:  36, national:  14 }],
    ['윌 리차드', { local:  40, national:  14 }],
    ['제일런 스미스', { local:  36, national:  14 }],
    ['타리 이슨', { local:  39, national:  14 }],
    ['캐리스 르버트', { local:  37, national:  14 }],
    ['스카티 피펜 주니어', { local:  39, national:  14 }],
    ['켈든 존슨', { local:  38, national:  14 }],
    ['프레셔스 아치우와', { local:  38, national:  14 }],
    ['론조 볼', { local:  38, national:  14 }],
    ['사디크 베이', { local:  37, national:  14 }],
    ['타일러 콜렉', { local:  40, national:  14 }],
    ['토린 프린스', { local:  38, national:  14 }],
    ['조쉬 오코기', { local:  37, national:  14 }],
    ['투마니 카마라', { local:  36, national:  14 }],
    ['패트릭 윌리엄스', { local:  40, national:  14 }],
    ['켄리치 윌리엄스', { local:  36, national:  14 }],
    ['허버트 존스', { local:  37, national:  14 }],
    ['하이메 하케즈 주니어', { local:  40, national:  14 }],
    ['제이 허프', { local:  36, national:  14 }],
    ['도노반 클링언', { local:  42, national:  14 }],
    ['콜 앤서니', { local:  36, national:  14 }],
    ['보그단 보그다노비치', { local:  37, national:  14 }],
    ['시모네 폰테키오', { local:  36, national:  14 }],
    ['개리 트렌트 주니어', { local:  36, national:  14 }],
    ['아이작 오코로', { local:  40, national:  14 }],
    ['드류 티미', { local:  36, national:  14 }],
    ['산티 알다마', { local:  39, national:  14 }],
    ['자바리 스미스 주니어', { local:  42, national:  14 }],
    ['잭 콜린스', { local:  36, national:  14 }],
    ['오비 토핀', { local:  38, national:  14 }],
    ['조나단 아이작', { local:  36, national:  14 }],
    ['조던 굿윈', { local:  36, national:  14 }],
    ['산드로 마무켈라쉬빌리', { local:  35, national:  13 }],
    ['베네딕트 매서린', { local:  37, national:  13 }],
    ['무사 디아바테', { local:  37, national:  13 }],
    ['자본테 그린', { local:  34, national:  13 }],
    ['자바리 워커', { local:  37, national:  13 }],
    ['제일런 클락', { local:  37, national:  13 }],
    ['조던 밀러', { local:  35, national:  13 }],
    ['개리 해리스', { local:  33, national:  13 }],
    ['제이든 하디', { local:  36, national:  13 }],
    ['루카 가르자', { local:  35, national:  13 }],
    ['줄리안 샴페니', { local:  37, national:  13 }],
    ['아리엘 헉포티', { local:  36, national:  13 }],
    ['브랜던 클락', { local:  33, national:  13 }],
    ['줄리안 스트로더', { local:  36, national:  13 }],
    ['클린트 카펠라', { local:  33, national:  13 }],
    ['펠레 라르손', { local:  37, national:  13 }],
    ['RJ 넴하드 주니어', { local:  35, national:  13 }],
    ['아미르 커피', { local:  33, national:  13 }],
    ['라이언 칼크브레너', { local:  37, national:  13 }],
    ['AJ 그린', { local:  35, national:  13 }],
    ['제일린 윌리엄스', { local:  38, national:  13 }],
    ['마커스 새서', { local:  34, national:  13 }],
    ['오차이 악바지', { local:  33, national:  13 }],
    ['고가 비타제', { local:  35, national:  13 }],
    ['제이션 테이트', { local:  33, national:  13 }],
    ['저스틴 샴페니', { local:  38, national:  13 }],
    ['카일 앤더슨', { local:  33, national:  13 }],
    ['마이크 콘리', { local:  43, national:  13 }],
    ['도리안 핀니-스미스', { local:  35, national:  13 }],
    ['자비에 틸먼', { local:  34, national:  13 }],
    ['스펜서 존스', { local:  36, national:  13 }],
    ['토마스 브라이언트', { local:  33, national:  13 }],
    ['드류 유뱅크스', { local:  33, national:  13 }],
    ['다리오 사리치', { local:  33, national:  13 }],
    ['애런 홀리데이', { local:  35, national:  13 }],
    ['빈스 윌리엄스 주니어', { local:  35, national:  13 }],
    ['본즈 하일랜드', { local:  35, national:  13 }],
    ['코비 샌더스', { local:  36, national:  13 }],
    ['조쉬 그린', { local:  33, national:  13 }],
    ['코비 브라운', { local:  33, national:  13 }],
    ['조던 맥러플린', { local:  33, national:  13 }],
    ['오쇼 이궈다로', { local:  33, national:  12 }],
    ['스비 미하일류크', { local:  31, national:  12 }],
    ['퀜튼 잭슨', { local:  31, national:  12 }],
    ['자말 샤히드', { local:  34, national:  12 }],
    ['VJ 엣지컴', { local:  43, national:  12 }],
    ['크리스찬 콜로코', { local:  31, national:  12 }],
    ['폴 리드', { local:  32, national:  12 }],
    ['두옵 리스', { local:  31, national:  12 }],
    ['제본 카터', { local:  31, national:  12 }],
    ['데빈 카터', { local:  34, national:  12 }],
    ['크레이그 포터 주니어', { local:  31, national:  12 }],
    ['달튼 크넥트', { local:  34, national:  12 }],
    ['지크 나지', { local:  35, national:  12 }],
    ['닉 클리포드', { local:  35, national:  12 }],
    ['케빈 맥컬러 주니어', { local:  34, national:  12 }],
    ['베일러 샤이어만', { local:  34, national:  12 }],
    ['대니 울프', { local:  40, national:  12 }],
    ['린디 워터스 III', { local:  31, national:  12 }],
    ['자레드 맥케인', { local:  39, national:  12 }],
    ['대니스 젠킨스', { local:  34, national:  12 }],
    ['제일런 피켓', { local:  32, national:  12 }],
    ['자말 케인', { local:  31, national:  12 }],
    ['자마리 부예야', { local:  32, national:  12 }],
    ['제리코 심스', { local:  31, national:  12 }],
    ['제이미슨 배틀', { local:  34, national:  12 }],
    ['라이언 롤린스', { local:  34, national:  12 }],
    ['크리스 머레이', { local:  31, national:  12 }],
    ['케이슨 월러스', { local:  38, national:  11 }],
    ['PJ 홀', { local:  32, national:  11 }],
    ['데렉 라이블리', { local:  37, national:  11 }],
    ['올랜도 로빈슨', { local:  28, national:  11 }],
    ['앤서니 길', { local:  30, national:  11 }],
    ['리드 셰퍼드', { local:  37, national:  11 }],
    ['케일럽 러브', { local:  32, national:  11 }],
    ['A.J. 로슨', { local:  28, national:  11 }],
    ['비스맥 비욤보', { local:  30, national:  11 }],
    ['아이재아 콜리어', { local:  36, national:  11 }],
    ['앤서니 블랙', { local:  37, national:  11 }],
    ['피트 낸스', { local:  30, national:  11 }],
    ['라이언 던', { local:  36, national:  11 }],
    ['알 호포드', { local:  41, national:  11 }],
    ['조나단 목보', { local:  32, national:  11 }],
    ['팻 코너튼', { local:  30, national:  11 }],
    ['자미르 영', { local:  29, national:  11 }],
    ['캠 스펜서', { local:  32, national:  11 }],
    ['테렌스 섀넌 주니어', { local:  30, national:  11 }],
    ['케본 루니', { local:  28, national:  11 }],
    ['마티스 타이불', { local:  28, national:  11 }],
    ['키숀 조지', { local:  36, national:  11 }],
    ['키튼 월러스', { local:  29, national:  11 }],
    ['막시 클레버', { local:  38, national:  11 }],
    ['콘 크니플', { local:  40, national:  11 }],
    ['아이재아 리버스', { local:  29, national:  11 }],
    ['빌랄 쿨리발리', { local:  36, national:  11 }],
    ['데릭 퀸', { local:  39, national:  11 }],
    ['제레미 소핸', { local:  37, national:  11 }],
    ['브랜던 칼슨', { local:  30, national:  11 }],
    ['제일런 웰스', { local:  37, national:  11 }],
    ['딜런 카드웰', { local:  30, national:  10 }],
    ['브라이스 맥고웬스', { local:  29, national:  10 }],
    ['구이 산토스', { local:  28, national:  10 }],
    ['네이콴 톰린', { local:  30, national:  10 }],
    ['노아 클라우니', { local:  35, national:  10 }],
    ['딜런 하퍼', { local:  37, national:  10 }],
    ['일라이자 하클리스', { local:  26, national:  10 }],
    ['테일러 헨드릭스', { local:  33, national:  10 }],
    ['조던 호킨스', { local:  29, national:  10 }],
    ['캠 존스', { local:  30, national:  10 }],
    ['안드레 잭슨 주니어', { local:  28, national:  10 }],
    ['카일 필리포우스키', { local:  33, national:  10 }],
    ['채즈 레이니어', { local:  29, national:  10 }],
    ['저스틴 에드워즈', { local:  34, national:  10 }],
    ['드루 스미스', { local:  27, national:  10 }],
    ['벤 셰퍼드', { local:  30, national:  10 }],
    ['트레 맨', { local:  30, national:  10 }],
    ['도미닉 발로우', { local:  34, national:  10 }],
    ['데일런 테리', { local:  28, national:  10 }],
    ['야닉 코난 니더하우저', { local:  34, national:  10 }],
    ['카를로 맛코비치', { local:  28, national:  10 }],
    ['줄리안 필립스', { local:  35, national:  10 }],
    ['JD 데이비슨', { local:  29, national:  10 }],
    ['올리비에-막생 프로스퍼', { local:  30, national:  10 }],
    ['이브스 미시', { local:  34, national:  10 }],
    ['스쿳 헨더슨', { local:  35, national:  10 }],
    ['제일런 타이슨', { local:  33, national:  10 }],
    ['그레이디 딕', { local:  33, national:  10 }],
    ['드와이트 파웰', { local:  34, national:  10 }],
    ['블라디슬라프 골딘', { local:  30, national:  10 }],
    ['니콜라 요비치', { local:  33, national:  10 }],
    ['케일럽 휴스탄', { local:  28, national:  10 }],
    ['데이론 홈즈 II', { local:  30, national:  10 }],
    ['켈리 올리닉', { local:  32, national:   9 }],
    ['트리스탄 부키체비치', { local:  31, national:   9 }],
    ['무하메드 게예', { local:  31, national:   9 }],
    ['세스 커리', { local:  32, national:   9 }],
    ['사이온 제임스', { local:  27, national:   9 }],
    ['브라이스 센사보', { local:  32, national:   9 }],
    ['자본 스몰', { local:  27, national:   9 }],
    ['조던 월쉬', { local:  32, national:   9 }],
    ['닉 스미스 주니어', { local:  31, national:   9 }],
    ['조니 퍼피', { local:  32, national:   9 }],
    ['마이카 피비', { local:  26, national:   9 }],
    ['재러스 워커', { local:  32, national:   9 }],
    ['아마리 윌리엄스', { local:  26, national:   9 }],
    ['마이카 포터', { local:  24, national:   9 }],
    ['아뎀 보나', { local:  30, national:   8 }],
    ['자코비 월터', { local:  28, national:   8 }],
    ['에이스 베일리', { local:  33, national:   8 }],
    ['놀란 트라오레', { local:  33, national:   8 }],
    ['타이리스 프록터', { local:  30, national:   8 }],
    ['월터 클레이튼 주니어', { local:  30, national:   8 }],
    ['맥스 슐가', { local:  24, national:   8 }],
    ['젯 하워드', { local:  28, national:   8 }],
    ['시디 시소코', { local:  30, national:   8 }],
    ['코디 윌리엄스', { local:  30, national:   8 }],
    ['막심 레이노', { local:  30, national:   8 }],
    ['레이제이 데니스', { local:  24, national:   8 }],
    ['롭 딜링엄', { local:  28, national:   8 }],
    ['제이스 리차드슨', { local:  30, national:   8 }],
    ['타이타이 워싱턴 주니어', { local:  25, national:   8 }],
    ['톨루 스미스', { local:  22, national:   8 }],
    ['데이비드 존스 가르시아', { local:  22, national:   7 }],
    ['조쉬 마이낫', { local:  27, national:   7 }],
    ['커티스 존스', { local:  21, national:   7 }],
    ['트레 존슨', { local:  32, national:   7 }],
    ['법 캐링턴', { local:  31, national:   7 }],
    ['모하메드 디아와라', { local:  32, national:   7 }],
    ['윌 라일리', { local:  31, national:   7 }],
    ['자카리 리사쉐', { local:  31, national:   7 }],
    ['더그 맥더못', { local:  26, national:   7 }],
    ['리암 맥닐리', { local:  31, national:   7 }],
    ['콜린 머레이-보일스', { local:  30, national:   6 }],
    ['니콜라스 바툼', { local:  32, national:   6 }],
    ['로날드 홀란드 II', { local:  30, national:   6 }],
    ['이고르 디오민', { local:  30, national:   6 }],
    ['드레이크 파웰', { local:  30, national:   6 }],
    ['케빈 러브', { local:  32, national:   6 }],
    ['브룩 로페즈', { local:  31, national:   6 }],
    ['카스파라스 야쿠쵸니스', { local:  29, national:   6 }],
    ['라클란 올브리히', { local:  23, national:   6 }],
    ['디안드레 조던', { local:  31, national:   6 }],
    ['GG 잭슨', { local:  30, national:   6 }],
    ['레오나르드 밀러', { local:  25, national:   6 }],
    ['파콤 다디엣', { local:  30, national:   6 }],
    ['에이사 뉴웰', { local:  27, national:   5 }],
    ['양 한센', { local:  26, national:   5 }],
    ['예레마이아 피어스', { local:  27, national:   5 }],
    ['티쟌 살라운', { local:  26, national:   5 }],
    ['벤 사라프', { local:  26, national:   5 }],
    ['카만 말루아치', { local:  27, national:   5 }],
    ['니콜라 토피치', { local:  27, national:   5 }],
    ['라얀 루퍼트', { local:  21, national:   5 }],
    ['우고 곤잘레스', { local:  27, national:   5 }],
    ['요안 베린저', { local:  24, national:   4 }],
    ['조 잉글스', { local:  25, national:   4 }],
    ['제프 그린', { local:  26, national:   4 }],
    ['로코 지카르스키', { local:  23, national:   4 }],
    ['AJ 존슨', { local:  24, national:   4 }],
    ['노아 펜다', { local:  24, national:   4 }],
    ['카일 라우리', { local:  24, national:   3 }],
    ['에릭 고든', { local:  19, national:   1 }],
]); 
